# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    brevo_api_key: '%env(BREVO_API_KEY)%'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $brevoApiKey: '%env(BREVO_API_KEY)%'
            string $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'
            string $appUrl: '%env(APP_URL)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\StripeService:
        arguments:
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
